"""
True Zero-Knowledge proof generation using snarkjs.
Replaces the mock implementation with actual ZK circuits.
"""

import asyncio
import hashlib
import json
import logging
import os
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Any, List, Tuple

from synapse_node.core.config import get_config

logger = logging.getLogger(__name__)


@dataclass
class ProofInput:
    """Input data for proof generation."""
    request_hash: str
    response_hash: str
    model_id: str
    timestamp: int
    gpu_utilization: float
    tokens_generated: int
    # Private inputs
    prompt: str
    response: str
    node_private_key: Optional[str] = None


@dataclass
class ZKProof:
    """Zero-knowledge proof structure."""
    proof_id: str
    proof_data: Dict[str, Any]  # snarkjs proof format
    public_inputs: List[str]
    circuit_id: str
    generated_at: int
    verification_key_hash: str
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "proof_id": self.proof_id,
            "proof": self.proof_data,
            "publicInputs": self.public_inputs,
            "circuit_id": self.circuit_id,
            "generated_at": self.generated_at,
            "verification_key_hash": self.verification_key_hash
        }


class ZKProofGenerator:
    """
    Generates real ZK proofs for inference work verification.
    Uses snarkjs with Groth16 protocol.
    """
    
    CIRCUIT_INFERENCE = "inference_work_v1"
    CIRCUIT_VERIFICATION_KEY = "inference_work_v1_vkey.json"
    
    def __init__(self, circuits_dir: Optional[Path] = None):
        self.config = get_config()
        self.circuits_dir = circuits_dir or self.config.proof_circuit_path
        self.circuits_dir = Path(self.circuits_dir)
        self.circuits_dir.mkdir(parents=True, exist_ok=True)
        
        # Paths to circuit files
        self.wasm_path = self.circuits_dir / f"{self.CIRCUIT_INFERENCE}.wasm"
        self.zkey_path = self.circuits_dir / f"{self.CIRCUIT_INFERENCE}_final.zkey"
        self.vkey_path = self.circuits_dir / self.CIRCUIT_VERIFICATION_KEY
        
        self._circuit_loaded = False
        self._verification_key_hash = ""
        
        self._initialize_circuit()
    
    def _initialize_circuit(self):
        """Initialize circuit files."""
        if not self.wasm_path.exists():
            logger.warning(f"Circuit WASM not found at {self.wasm_path}")
            logger.warning("Proof generation will use fallback mode until circuits are compiled")
            return
        
        if not self.zkey_path.exists():
            logger.warning(f"Proving key not found at {self.zkey_path}")
            return
        
        if not self.vkey_path.exists():
            logger.warning(f"Verification key not found at {self.vkey_path}")
            return
        
        # Calculate verification key hash
        vkey_content = self.vkey_path.read_text()
        self._verification_key_hash = hashlib.sha256(vkey_content.encode()).hexdigest()
        self._circuit_loaded = True
        
        logger.info(f"ZK circuit loaded: {self.CIRCUIT_INFERENCE}")
        logger.info(f"Verification key hash: {self._verification_key_hash[:16]}...")
    
    def _hash_string(self, data: str) -> str:
        """Generate SHA256 hash of string."""
        return hashlib.sha256(data.encode()).hexdigest()
    
    def _hash_dict(self, data: Dict) -> str:
        """Generate deterministic hash of dictionary."""
        json_str = json.dumps(data, sort_keys=True, separators=(',', ':'))
        return self._hash_string(json_str)
    
    async def generate_proof(
        self,
        input_data: ProofInput,
        circuit_type: str = CIRCUIT_INFERENCE
    ) -> ZKProof:
        """
        Generate a real ZK proof using snarkjs.
        
        The circuit proves:
        1. The node processed the request (hashes match)
        2. Response was generated by specified model
        3. Work was done within time constraints
        4. GPU utilization is within bounds
        """
        start_time = time.time()
        
        proof_id = f"proof-{input_data.timestamp}-{self._hash_string(input_data.request_hash)[:16]}"
        
        if not self._circuit_loaded:
            logger.warning("Circuit not loaded, generating placeholder proof")
            return self._generate_placeholder_proof(proof_id, input_data, circuit_type)
        
        try:
            # Prepare witness inputs
            witness_inputs = self._prepare_witness_inputs(input_data)
            
            # Generate witness using snarkjs
            witness = await self._generate_witness(witness_inputs)
            
            # Generate proof
            proof = await self._groth16_prove(witness)
            
            # Prepare public inputs
            public_inputs = [
                input_data.request_hash,
                input_data.response_hash,
                self._hash_string(input_data.model_id),
                str(input_data.tokens_generated),
                str(input_data.timestamp)
            ]
            
            generation_time = time.time() - start_time
            
            logger.info(
                f"Generated ZK proof {proof_id[:16]}... "
                f"({input_data.tokens_generated} tokens) in {generation_time:.3f}s"
            )
            
            return ZKProof(
                proof_id=proof_id,
                proof_data=proof,
                public_inputs=public_inputs,
                circuit_id=circuit_type,
                generated_at=int(time.time()),
                verification_key_hash=self._verification_key_hash
            )
            
        except Exception as e:
            logger.error(f"Proof generation failed: {e}")
            raise
    
    def _prepare_witness_inputs(self, input_data: ProofInput) -> Dict[str, Any]:
        """Prepare inputs for witness generation."""
        # Convert hashes to field elements (simplified)
        request_hash_int = int(input_data.request_hash[:32], 16)
        response_hash_int = int(input_data.response_hash[:32], 16)
        model_hash_int = int(self._hash_string(input_data.model_id)[:32], 16)
        
        return {
            # Public inputs
            "requestHash": str(request_hash_int),
            "responseHash": str(response_hash_int),
            "modelHash": str(model_hash_int),
            "tokensGenerated": input_data.tokens_generated,
            "timestamp": input_data.timestamp,
            "gpuUtilization": int(input_data.gpu_utilization * 100),  # Scale to integer
            
            # Private inputs
            "promptHash": int(self._hash_string(input_data.prompt)[:32], 16),
            "responseHashPrivate": int(self._hash_string(input_data.response)[:32], 16)
        }
    
    async def _generate_witness(self, inputs: Dict[str, Any]) -> Path:
        """Generate witness using snarkjs calculatewitness."""
        # Create temporary input file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(inputs, f)
            input_file = f.name
        
        # Create temporary witness file
        witness_file = tempfile.mktemp(suffix='.wtns')
        
        try:
            # Run snarkjs to generate witness
            cmd = [
                'snarkjs',
                'wtns',
                'calculate',
                str(self.wasm_path),
                input_file,
                witness_file
            ]
            
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await proc.communicate()
            
            if proc.returncode != 0:
                raise RuntimeError(f"Witness generation failed: {stderr.decode()}")
            
            return Path(witness_file)
            
        finally:
            os.unlink(input_file)
    
    async def _groth16_prove(self, witness_path: Path) -> Dict[str, Any]:
        """Generate Groth16 proof using snarkjs."""
        proof_file = tempfile.mktemp(suffix='.json')
        
        try:
            cmd = [
                'snarkjs',
                'groth16',
                'prove',
                str(self.zkey_path),
                str(witness_path),
                proof_file
            ]
            
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await proc.communicate()
            
            if proc.returncode != 0:
                raise RuntimeError(f"Proof generation failed: {stderr.decode()}")
            
            # Read and parse proof
            with open(proof_file, 'r') as f:
                proof_data = json.load(f)
            
            return proof_data
            
        finally:
            os.unlink(proof_file)
            os.unlink(str(witness_path))
    
    def verify_proof(
        self,
        proof: ZKProof,
        expected_public_inputs: Optional[List[str]] = None
    ) -> bool:
        """
        Verify a ZK proof using snarkjs.
        
        Can be called by:
        - Client to verify work was done correctly
        - Smart contract (with on-chain verification key)
        - Other nodes during consensus
        """
        if not self._circuit_loaded and not proof.verification_key_hash:
            logger.warning("Cannot verify: no verification key available")
            return False
        
        try:
            # Verify VK hash matches
            if proof.verification_key_hash != self._verification_key_hash:
                logger.warning("Verification key mismatch")
                return False
            
            # Run snarkjs verify
            # In production, this would be done on-chain or with pre-compiled verifier
            return self._groth16_verify(proof)
            
        except Exception as e:
            logger.error(f"Proof verification error: {e}")
            return False
    
    def _groth16_verify(self, proof: ZKProof) -> bool:
        """Run snarkjs groth16 verify."""
        try:
            # Create temporary proof file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
                json.dump(proof.proof_data, f)
                proof_file = f.name
            
            # Create public inputs file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
                json.dump(proof.public_inputs, f)
                public_file = f.name
            
            # Run snarkjs verify
            cmd = [
                'snarkjs',
                'groth16',
                'verify',
                str(self.vkey_path),
                public_file,
                proof_file
            ]
            
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            
            os.unlink(proof_file)
            os.unlink(public_file)
            
            return result.returncode == 0 and "OK" in result.stdout
            
        except Exception as e:
            logger.error(f"Groth16 verify error: {e}")
            return False
    
    def _generate_placeholder_proof(
        self,
        proof_id: str,
        input_data: ProofInput,
        circuit_type: str
    ) -> ZKProof:
        """Generate placeholder proof when circuits not available."""
        logger.warning("Generating placeholder proof - NOT CRYPTOGRAPHICALLY SECURE")
        
        # Create a proof structure that will fail verification
        # This ensures nodes can't cheat when circuits are missing
        return ZKProof(
            proof_id=proof_id,
            proof_data={
                "pi_a": ["0", "0"],
                "pi_b": [["0", "0"], ["0", "0"]],
                "pi_c": ["0", "0"],
                "protocol": "placeholder"
            },
            public_inputs=[
                input_data.request_hash,
                input_data.response_hash,
                self._hash_string(input_data.model_id),
                str(input_data.tokens_generated),
                str(input_data.timestamp)
            ],
            circuit_id=circuit_type,
            generated_at=int(time.time()),
            verification_key_hash="placeholder"
        )
    
    def create_proof_input(
        self,
        request_data: Dict[str, Any],
        response_data: Dict[str, Any],
        model_id: str,
        tokens_generated: int,
        gpu_utilization: float = 0.0
    ) -> ProofInput:
        """Create proof input from request/response data."""
        request_hash = self._hash_dict(request_data)
        response_hash = self._hash_dict(response_data)
        
        return ProofInput(
            request_hash=request_hash,
            response_hash=response_hash,
            model_id=model_id,
            timestamp=int(time.time()),
            gpu_utilization=gpu_utilization,
            tokens_generated=tokens_generated,
            prompt=request_data.get("prompt", ""),
            response=response_data.get("text", "")
        )
    
    def estimate_proof_cost(self, tokens_generated: int) -> Dict[str, float]:
        """Estimate computational cost of proof generation."""
        # Groth16 proof generation costs
        base_time = 2.0  # 2 seconds base
        per_token_time = 0.0001  # Very small per-token overhead
        
        estimated_time = base_time + (tokens_generated * per_token_time)
        
        return {
            "estimated_time_seconds": estimated_time,
            "memory_required_mb": 1024,  # snarkjs needs ~1GB
            "circuit_size_mb": 50 if self.wasm_path.exists() else 0
        }
    
    def get_verification_key(self) -> Optional[Dict]:
        """Get the verification key for on-chain verification."""
        if not self.vkey_path.exists():
            return None
        
        with open(self.vkey_path, 'r') as f:
            return json.load(f)


class ProofBatch:
    """Batch multiple proofs for efficient verification."""
    
    def __init__(self, max_size: int = 100):
        self.max_size = max_size
        self.proofs: List[ZKProof] = []
        self.merkle_root: Optional[str] = None
    
    def add(self, proof: ZKProof) -> bool:
        """Add a proof to the batch."""
        if len(self.proofs) >= self.max_size:
            return False
        self.proofs.append(proof)
        self.merkle_root = None
        return True
    
    def compute_merkle_root(self) -> str:
        """Compute Merkle root of batched proofs."""
        if self.merkle_root:
            return self.merkle_root
        
        # Build Merkle tree
        leaves = [p.proof_id for p in self.proofs]
        
        while len(leaves) > 1:
            if len(leaves) % 2 == 1:
                leaves.append(leaves[-1])  # Duplicate last if odd
            
            new_leaves = []
            for i in range(0, len(leaves), 2):
                combined = leaves[i] + leaves[i + 1]
                new_leaves.append(hashlib.sha256(combined.encode()).hexdigest())
            leaves = new_leaves
        
        self.merkle_root = leaves[0] if leaves else ""
        return self.merkle_root
    
    def get_merkle_proof(self, index: int) -> List[str]:
        """Get Merkle proof for a specific proof."""
        if index >= len(self.proofs):
            return []
        
        leaves = [p.proof_id for p in self.proofs]
        proof = []
        
        while len(leaves) > 1:
            if len(leaves) % 2 == 1:
                leaves.append(leaves[-1])
            
            sibling_idx = index + 1 if index % 2 == 0 else index - 1
            proof.append(leaves[sibling_idx])
            
            index //= 2
            new_leaves = []
            for i in range(0, len(leaves), 2):
                combined = leaves[i] + leaves[i + 1]
                new_leaves.append(hashlib.sha256(combined.encode()).hexdigest())
            leaves = new_leaves
        
        return proof
    
    def clear(self):
        """Clear all proofs from batch."""
        self.proofs = []
        self.merkle_root = None


# Global instance
_proof_generator: Optional[ZKProofGenerator] = None


def get_proof_generator() -> ZKProofGenerator:
    """Get global ZK proof generator instance."""
    global _proof_generator
    if _proof_generator is None:
        _proof_generator = ZKProofGenerator()
    return _proof_generator
