import type { VercelRequest, VercelResponse } from '@vercel/node';

const DEMO_MODE = process.env.VITE_DEMO_MODE === 'true' || !process.env.BACKEND_URL;
const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:8080';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { path } = req.query;
  const endpoint = Array.isArray(path) ? path.join('/') : path || '';

  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Demo mode: return mock responses
  if (DEMO_MODE) {
    return handleDemoMode(req, res, endpoint);
  }

  // Proxy to real backend
  try {
    const url = `${BACKEND_URL}/v1/${endpoint}`;
    const response = await fetch(url, {
      method: req.method,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': req.headers.authorization || '',
      },
      body: req.method !== 'GET' ? JSON.stringify(req.body) : undefined,
    });

    const data = await response.json().catch(() => null);
    return res.status(response.status).json(data);
  } catch (error) {
    console.error('Proxy error:', error);
    return res.status(502).json({ 
      error: 'Backend unavailable',
      message: 'The backend service is not responding. Running in fallback mode.'
    });
  }
}

function handleDemoMode(req: VercelRequest, res: VercelResponse, endpoint: string) {
  switch (endpoint) {
    case 'health':
      return res.status(200).json({
        status: 'ok',
        version: '1.0.0-demo',
        mode: 'demo',
        timestamp: new Date().toISOString(),
      });

    case 'stats':
      return res.status(200).json({
        nodes_online: 47,
        total_capacity: '2.4 PFLOPS',
        avg_latency_ms: 89,
        requests_24h: 12473,
        active_jobs: 12,
        network_health: 'healthy',
      });

    case 'keys':
      if (req.method === 'POST') {
        const key = `synapse_${Array.from({length: 32}, () => Math.random().toString(36)[2]).join('')}`;
        return res.status(201).json({
          api_key: key,
          created_at: new Date().toISOString(),
          tier: 'standard',
        });
      }
      return res.status(405).json({ error: 'Method not allowed' });

    case 'chat/completions':
      if (req.method === 'POST') {
        // Simulate streaming response
        res.setHeader('Content-Type', 'text/event-stream');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');

        const mockResponse = `This is a demo response from Synapse Gateway. In production, this would be generated by a distributed network of GPU nodes.\n\nYour prompt was processed through:\n- Gateway router (Melbourne, AU)\n- Node selection (latency-optimized)\n- Execution node (RTX 4090 cluster)\n\nDemo mode active - no actual inference performed.`;

        const chunks = mockResponse.split(' ');
        let index = 0;

        const stream = setInterval(() => {
          if (index >= chunks.length) {
            res.write(`data: [DONE]\n\n`);
            res.end();
            clearInterval(stream);
            return;
          }

          const chunk = chunks.slice(index, index + 3).join(' ');
          const data = {
            id: 'demo-' + Date.now(),
            object: 'chat.completion.chunk',
            created: Math.floor(Date.now() / 1000),
            model: req.body?.model || 'synapse-demo',
            choices: [{
              index: 0,
              delta: { content: chunk + ' ' },
              finish_reason: null,
            }],
          };

          res.write(`data: ${JSON.stringify(data)}\n\n`);
          index += 3;
        }, 50);

        return;
      }
      return res.status(405).json({ error: 'Method not allowed' });

    case 'models':
      return res.status(200).json({
        object: 'list',
        data: [
          { id: 'synapse-llama-3-70b', object: 'model', owned_by: 'synapse' },
          { id: 'synapse-mixtral-8x22b', object: 'model', owned_by: 'synapse' },
          { id: 'synapse-llama-3-8b', object: 'model', owned_by: 'synapse' },
        ],
      });

    case 'jobs':
      return res.status(200).json({
        jobs: [
          {
            id: 'job-demo-001',
            status: 'completed',
            model: 'synapse-llama-3-70b',
            created_at: new Date(Date.now() - 3600000).toISOString(),
            completed_at: new Date().toISOString(),
            latency_ms: 1245,
          },
        ],
      });

    default:
      return res.status(404).json({ 
        error: 'Not found',
        message: `Endpoint /v1/${endpoint} not implemented in demo mode`
      });
  }
}
